### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by CharlieNoodl** [Rajaniraiyn/modern-js-boilerplate#15]
Hi,

I have been looking at your project and it is looking good.
However, testing is the key to prevent bugs from happening and I noticed you lack tests. 

I am working on a project called Ponicode, it is a VS Code extension that writes AI-generated unit tests. I think it could help you test your projects quickly.
It would be awesome if you could check it out on the VS Code Market Place, I would love to have some feedback.
Here is the link to the marketplace if you feel like trying it out: https://marketplace.visualstudio.com/items?itemName=ponicode.ponicode

Have a nice day,

Charlie.

**Comment by Rajaniraiyn** [comment]
@CharlieNoodl Thank you so much I'm sure that I will try to use it in this project and my another project [Raj Lang - JS](https://github.com/rajlang/Raj-JavaScript)
